### ISSUE TITLE
Installed but now shows code rather than page builder content

### ISSUE THREAD

**Issue by ben64digital** [Angrycreative/ACF-Page-Builder-Field#1]
I installed the plugin and activated as described in the Readme.  I then created a custom field, selected the page builder option and put content in.  However, it shows the following on the front-end of the site rather than the title and text I put in using the builder.

Did I miss something/a step?

Thanks :-)

{"widgets":[{"title":"Footer Text Title","text":"

Footer Content goes here…

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
","text_selected_editor":"tinymce","autop":"on","_sow_form_id":"56b49f470d528","panels_info":{"class":"SiteOrigin_Widget_Editor_Widget","raw":true,"grid":0,"cell":0,"id":0,"style":{"class":"","widget_css":"","iw-visible-screen":"iw-all","iw-visible-layout":"iw-all","padding":"","background":"","background_image_attachment":"0","background_display":"tile","border_color":"","font_color":""}}}],"grids":[{"cells":1,"style":{}}],"grid_cells":[{"grid":0,"weight":1}]}

**Comment by pelmered** [comment]
Hello, 

Thank you for trying this. I'm sorry for the lack of documentation, we are working on that. 

The plugins is built to be used with ACF's Flexible Content fields, like described here:  http://www.advancedcustomfields.com/resources/flexible-content/

When you have that set up you need a special rule for the output of the page builder field. Add one conditional that checks `get_row_layout()` like in the example in the link. 

```
if( get_row_layout() == 'page_builder' )
{
        if( function_exists( 'get_page_builder_field' ))
        {
            echo get_page_builder_field( 'page_builder_data' );
        }
}
elseif( get_row_layout() == 'download' )
{
```

If you only use the normal `get_sub_field()` you will get the raw page builder data that you provided. 

I hope that helps.

**Comment by ben64digital** [comment]
Thanks for the quick reply.  I will give that a go.

**Comment by moelleer** [comment]
Hi,

I made a little fix for the plugin so that you can use it without nestling it in a flexible content/repeater field.

You can try it out with this code now:

`echo get_page_builder_field( 'page_builder_data' );`

**Comment by ben64digital** [comment]
Absolutely perfect.  Works a treat.  Thank you both so much.
