### ISSUE TITLE
Acf Page Builder Field 1.0.1 + page builder 2.5.2 incompatibility 

### ISSUE THREAD

**Issue by DigiDigi-doron** [Angrycreative/ACF-Page-Builder-Field#12]
I updated the plugin to Version 1.0.1. It solved the **Fatal error Call to undefined function siteorigin_panels_generate_css()**. But now I’m getting:

**Warning : explode() expects parameter 2 to be string, array given in ***/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337**

**Warning: array_merge(): Argument #2 is not an array in ***/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337**

Can you help?

Thanks

**Comment by viktorfroberg** [comment]
Hi! 
I've been looking at this problem today and think I have a fix for it [here](https://github.com/Angrycreative/ACF-Page-Builder-Field/tree/PB-2.5-fix). Can your try it out and see if it fixes your problems?

**Comment by DigiDigi-doron** [comment]
Hi man!
Thanks for your reply.

The error massages are gone - but it still doesn't work OK.
Settings like class, id, BG image padding etc added to a widget  (i,e SiteOrigin Editor)  on the "Widget Styles" section of the builder are not showing in the front end. (row settings seems to work fine).

I will be happy to provide access credentials or any other info you need to help you solve the problem
 
Thanks!

**Comment by viktorfroberg** [comment]
Hi again! 
I just pushed a fix for the missing widget information, try it out [here](https://github.com/Angrycreative/ACF-Page-Builder-Field/tree/PB-2.5-fix).

Let me know if it fixes your problems!

**Comment by DigiDigi-doron** [comment]
Hey man - sorry for the late response - I had to set up a proper staging environment.
I noticed some strange behaviors on rows.

1. When you assign a BG color to a row - it won't show until you add to that row a custom class. Removing the class also causes the BG color to be removed.  

2. The Row ID and Cell Class under Row Styles > attributes also won't show on the front end.

Thanks again!

Doron

**Comment by viktorfroberg** [comment]
Hi! 
Thanks for trying it out! 
At first that sounded like one strange bug, but after looking at the code it kind of made sense! 😅 
I pushed a fix to the [same branch as before](https://github.com/Angrycreative/ACF-Page-Builder-Field/tree/PB-2.5-fix). 

Let me know how it works out! 

/ Viktor

**Comment by DigiDigi-doron** [comment]
Hey
Did some further testing. Found two Issues:

1. When you set a row to be "full width starched" in Row > Layout > Row Layout - it won't work. In the "Regular" page builder a full width starched row gets a `data-stretch-type="full-stretched"` and it seem that there is Some JS targeted to it to make it full width and starched.

2.Under Row Row Styles > Cell Class. Setting a cell class doesn't show on front End,

Thanks Again! 
We relay heavily on your plugin in our site and your help is really valuable.

Doron

**Comment by viktorfroberg** [comment]
Hey! 
Thanks for the report! 
Pushed a new fix, try it out [here](https://github.com/Angrycreative/ACF-Page-Builder-Field/tree/PB-2.5-fix).

/ Viktor

**Comment by DigiDigi-doron** [comment]
Looks Good!

When it will be released to the WP repository?
What version number will it get?

**Comment by viktorfroberg** [comment]
Hi! 
Thanks for helping out! The new version is released and the version number is 1.0.3!

/ Viktor
