### ISSUE TITLE
Fatal error: Call to undefined function is_plugin_active()

### ISSUE THREAD

**Issue by cargeo** [Angrycreative/ACF-Page-Builder-Field#2]
After plugin activation I get the following error:
`Fatal error: Call to undefined function is_plugin_active() in /...../wp-content/plugins/acf-page-builder-field/acf-page_builder_field.php on line 70`

(System: WP, ACFpro, Page Builder)

**Comment by pelmered** [comment]
Hello @cargeo,

It should work now.

**Comment by cargeo** [comment]
Thanks, now it works.
