### ISSUE TITLE
Support for Advanced Custom Fields version 4

### ISSUE THREAD

**Issue by pelmered** [Angrycreative/ACF-Page-Builder-Field#3]

**Comment by pelmered** [comment]
As ACF will make version 5 free during 2015 we don't feel that we need to add support for version 4 anymore. Source: https://www.advancedcustomfields.com/blog/acf-2016-year-review/

**Comment by keepsmilyn** [comment]
Current free version of ACF is 4.4.12, see here: https://wordpress.org/plugins/advanced-custom-fields/

Revised post: Just found this info on how to update to version 5: https://www.advancedcustomfields.com/resources/upgrade-guide-version-5/
